[project]
name = "med-sar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "torch",
    "transformers",
    "datasets",
    "accelerate",
    "sentence-transformers",
    "scikit-learn",
    "numpy",
    "pandas",
    "pyyaml",
    "tqdm",
    "rich",
    "wandb",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "ipykernel",
]

[tool.setuptools.packages.find]
where = ["src"]